# Generated by Django 3.2.7 on 2021-09-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=300)),
                ('station_id', models.CharField(max_length=300)),
                ('action', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
